parameters:
    tq_extdirect.debug: false

services:
    tq_extdirect.ext_direct_api_controller:
        class: TQ\Bundle\ExtDirectBundle\Controller\ApiController
        public: true
        arguments:
            - "@tq_extdirect.endpoint_manager"
            - "@router"

    tq_extdirect.ext_direct_router_controller:
        class: TQ\Bundle\ExtDirectBundle\Controller\RouterController
        public: true
        arguments:
            - "@tq_extdirect.endpoint_manager"

    tq_extdirect.templating_helper:
        class: TQ\Bundle\ExtDirectBundle\Helper\TemplatingHelper
        arguments: [ "@router" ]

    tq_extdirect.ext_direct_extension:
        class: TQ\Bundle\ExtDirectBundle\Twig\ExtDirectExtension
        arguments: [ "@tq_extdirect.templating_helper" ]
        tags:
            - { name: twig.extension }

    tq_extdirect.templating.helper.extdirect_helper:
        class: TQ\Bundle\ExtDirectBundle\Templating\Helper\ExtDirectHelper
        arguments: [ "@tq_extdirect.templating_helper" ]
        tags:
            - { name: templating.helper, alias: tq_extdirect }

    tq_extdirect.endpoint_manager:
        class: TQ\ExtDirect\Service\EndpointManager
        public: true

    tq_extdirect.router.request_factory:
        class: TQ\ExtDirect\Router\RequestFactory

    tq_extdirect.metadata.annotation_driver:
        class: TQ\ExtDirect\Metadata\Driver\AnnotationDriver
        public: false
        arguments:
            - "@annotation_reader"

    tq_extdirect.metadata.cache.file:
        class: Metadata\Cache\FileCache
        public: false
        arguments:
            - ~ #directory

    tq_extdirect.metadata.cache:
        alias: tq_extdirect.metadata.cache.file
        public: false

    tq_extdirect.metadata_factory:
        class: Metadata\MetadataFactory
        public: false
        arguments:
            - "@tq_extdirect.metadata.annotation_driver"
            - Metadata\ClassHierarchyMetadata
            - "%tq_extdirect.debug%"
        calls:
            - [ setCache, [ "@?tq_extdirect.metadata.cache" ] ]

    tq_extdirect.naming_strategy:
        class: TQ\ExtDirect\Service\DefaultNamingStrategy
        public: false

    tq_extdirect.service_path_loader:
        class: TQ\ExtDirect\Service\PathServiceLoader
        public: false
        abstract: true
        arguments:
            - ~ # directories

    tq_extdirect.service_registry:
        class: TQ\ExtDirect\Service\DefaultServiceRegistry
        public: false
        abstract: true
        arguments:
            - "@tq_extdirect.metadata_factory"
            - "@tq_extdirect.naming_strategy"

    tq_extdirect.service_description_factory:
        class: TQ\ExtDirect\Description\ServiceDescriptionFactory
        public: false
        abstract: true
        arguments:
            - ~ # service registry
            - ~ # namespace
            - ~ # enableBuffer
            - ~ # bufferLimit
            - ~ # timeout
            - ~ # maxRetries

    tq_extdirect.service_factory:
        class: TQ\ExtDirect\Service\ContainerServiceFactory
        arguments: [ "@service_container" ]

    tq_extdirect.service_resolver:
        class: TQ\ExtDirect\Router\ServiceResolver
        public: false
        abstract: true
        arguments:
            - ~ # service registry
            - "@tq_extdirect.service_factory"

    tq_extdirect.router:
        class: TQ\ExtDirect\Router\Router
        public: false
        abstract: true
        arguments:
            - ~ # service resolver
            - "@?event_dispatcher"
            - "%tq_extdirect.debug%"

    tq_extdirect.endpoint:
        class: TQ\ExtDirect\Service\Endpoint
        public: false
        abstract: true
        arguments:
            - ~ # id
            - ~ # service description factory
            - ~ # router
            - "@tq_extdirect.router.request_factory"
            - ~ # descriptor
            - "%tq_extdirect.debug%"

    tq_extdirect.router.argument_validator:
        class: TQ\ExtDirect\Router\ArgumentValidator
        public: false
        arguments: [ "@validator", true ]

    tq_extdirect.router.listener.argument_validation:
        class: TQ\ExtDirect\Router\EventListener\ArgumentValidationListener
        arguments: [ "@tq_extdirect.router.argument_validator" ]
        tags:
            - { name: kernel.event_subscriber }

    tq_extdirect.router.argument_converter:
        class: TQ\ExtDirect\Router\ArgumentConverter
        public: false
        arguments: [ "@jms_serializer" ]

    tq_extdirect.router.listener.argument_conversion:
        class: TQ\ExtDirect\Router\EventListener\ArgumentConversionListener
        arguments: [ "@tq_extdirect.router.argument_converter" ]
        tags:
            - { name: kernel.event_subscriber }

    tq_extdirect.router.authorization_checker:
        class: TQ\ExtDirect\Router\AuthorizationChecker
        public: false
        arguments:
            - "@security.expression_language"
            - "@security.authentication.trust_resolver"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@?security.role_hierarchy"

    tq_extdirect.router.listener.authorization:
        class: TQ\ExtDirect\Router\EventListener\AuthorizationListener
        arguments: [ "@tq_extdirect.router.authorization_checker" ]
        tags:
            - { name: kernel.event_subscriber }

    tq_extdirect.router.result_converter:
        class: TQ\ExtDirect\Router\ResultConverter
        public: false
        arguments: [ "@jms_serializer" ]

    tq_extdirect.router.listener.result_conversion:
        class: TQ\ExtDirect\Router\EventListener\ResultConversionListener
        arguments: [ "@tq_extdirect.router.result_converter" ]
        tags:
            - { name: kernel.event_subscriber }

    tq_extdirect.router.listener.stopwatch:
        class: TQ\ExtDirect\Router\EventListener\StopwatchListener
        arguments: [ "@?debug.stopwatch" ]
        tags:
            - { name: kernel.event_subscriber }

    tq_extdirect.router.listener.dump:
        class: TQ\Bundle\ExtDirectBundle\Router\DumpListener
        arguments: [ "@?data_collector.dump" ]
        tags:
            - { name: kernel.event_subscriber }

    tq_extdirect.router.request_logger:
        class: TQ\Bundle\ExtDirectBundle\Router\RequestLogger
        public: false

    tq_extdirect.router.listener.request_log:
        class: TQ\Bundle\ExtDirectBundle\Router\RequestLogListener
        arguments:
            - "@tq_extdirect.router.request_logger"
            - "@?logger"
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: tq_extdirect }

    tq_extdirect.data_collector.request_collector:
        class: TQ\Bundle\ExtDirectBundle\DataCollector\RequestCollector
        public: false
        arguments:
            - "@tq_extdirect.router.request_logger"
        tags:
            - { name: data_collector, id: tq_extdirect.request_collector, template: "@TQExtDirect/data_collector/request_collector.html.twig" }
