tq_extdirect_api:
    path: /{endpoint}/api.{_format}
    methods: [GET]
    requirements:
        _format: js|json
    defaults:
        _controller: tq_extdirect.ext_direct_api_controller:apiAction

tq_extdirect_router:
    path: /{endpoint}/router
    methods: [POST]
    defaults:
        _controller: tq_extdirect.ext_direct_router_controller::routerAction
